### ISSUE TITLE
No devices showing

### ISSUE THREAD

**Issue by jesshannon** [MathisBurger/homebridge-dashboard#1]
**Describe The Bug:**
No devices show on dashboard

**To Reproduce:**
Installed dashboard, added different values for UniqueID

**Expected behavior:**
Accessories show on dashboard

**Logs:**

```
[18/05/2023, 12:39:58] Loaded plugin: homebridge-dashboard@1.3.0
[18/05/2023, 12:39:58] Registering platform 'homebridge-dashboard.Homebridge Dashboard'
[18/05/2023, 12:40:00] [Dashboard] Initializing Homebridge Dashboard platform...
[18/05/2023, 12:40:00] [Dashboard] Finished initializing platform: Dashboard
[18/05/2023, 12:40:00] [Dashboard] /usr/lib/node_modules/homebridge-dashboard/dist/static
[18/05/2023, 12:40:00] [Dashboard] Started homebridge dashboard on port 18081
```

**Plugin Config:**

```json
{
    "name": "Dashboard",
    "port": 18081,
    "tabs": [
        {
            "devices": [
                "00124B00226FD2EF",
                "1",
                "2",
                "6",
                "14"
            ],
            "name": "Guest Room"
        }
    ],
    "platform": "Homebridge Dashboard"
}
```

**Screenshots:**
<img width="544" alt="image" src="https://github.com/MathisBurger/homebridge-dashboard/assets/673246/946fcec4-7be5-4a00-abc7-93686dc471cc">

**Environment:**

* **Plugin Version**: 1.3.0
* **Homebridge Version**: v1.6.0
* **Node.js Version**: v14.21.2
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by MathisBurger** [comment]
What type of accessories are you using? I`ve just tested simple light switches. 
Furthermore, what type of browser are you using? If you are using Chrome or Firefox please check if there are any failed http requests or errors in the console.

**Comment by jesshannon** [comment]
Just light switches. There's no errors in the console. I can see it load the tabConfiguration, then it opens a websocket and receives a "state-changed" message every couple of seconds, but the data attribute in the message is always an empty array.

**Comment by MathisBurger** [comment]
As far as I can see, your pin is missing. Therefore, you should add it to the configuration. If you are using config-ui-x you can see your code on the dashboard.
The pin is required to fetch the accessories from the homebridge API. 
You should also start homebridge in insecure mode. 

<img width="360" alt="Screenshot 2023-05-22 at 15 11 28" src="https://github.com/MathisBurger/homebridge-dashboard/assets/57145815/4be18341-999c-4f3a-a02d-60c32f9db023">
